### ISSUE TITLE
Alt Title for Player View

### ISSUE THREAD

**Issue by mouse0270** [mouse0270/kasper#12]
Provide an option to allow Game Master to have an Alternative title for Player viewable Trackers.

For example, If Faction is called **Really Evil People**, it would be useful to instead display **Totally Kool Magic People** so that players see the faction, they will only see **Totally Kool Magic People** in the tracker.

Provide a way for the GM to see both titles and to remove Alt Title if GM decides to show real faction title to players.

Does this sound what you are looking for @GorgoPrimus?

**Comment by GorgoPrimus** [comment]
Perfect. Thanks!

**Comment by mouse0270** [comment]
included in v1.1.3
