### ISSUE TITLE
1.1.0 does not install properly or work at all

### ISSUE THREAD

**Issue by MotoMoto1234** [mouse0270/kasper#13]
Something is wrong with the module, it doesn't function at all in 1.1.0.  
![image](https://github.com/mouse0270/kasper/assets/116308065/251b27d1-e5e4-4d44-9de3-ef7ff602472c)
![image](https://github.com/mouse0270/kasper/assets/116308065/b5a410e9-68ee-4f74-ae06-f0b22ad6be2a)

**Comment by MotoMoto1234** [comment]
![image](https://github.com/mouse0270/kasper/assets/116308065/c05c31b4-f8b3-4aeb-bb75-50fb23714197)
![image](https://github.com/mouse0270/kasper/assets/116308065/4ce4123d-61ce-41f4-9cfa-f37c3d5728fb)

**Comment by mouse0270** [comment]
resolved in [v1.1.2](https://github.com/mouse0270/kasper/releases/tag/1.1.2)
