### ISSUE TITLE
Mouse Scroll Issue

### ISSUE THREAD

**Issue by MotoMoto1234** [mouse0270/kasper#6]
If you have a really long list of factions, people naturally scroll down with the mouse scroll and it can cause factions to change instead of scroll down, maybe turn off mouse wheel adjusting the faction levels.

**Comment by mouse0270** [comment]
That makes sense and you know, I ran into this issue a few times, A smarter me would have thought to do this. haha

**Comment by mouse0270** [comment]
Added setting to disable mouse wheel from changing value unless holding the `ctrl` key

Should be resolved in [v1.1.0](https://github.com/mouse0270/kasper/releases/tag/1.1.0)
