### ISSUE TITLE
Bug: On v10 the bar colours don't show up

### ISSUE THREAD

**Issue by GorgoPrimus** [mouse0270/kasper#9]
I know V10 is on the way out, but the colourized bars don't work on it and that's sad for my current world/server/campaign.

https://i.imgur.com/0RhVjFU.jpg

**Comment by mouse0270** [comment]
Well this is weird, that is just CSS... so it shouldn't matter the version. 

Could you tell me the browser and version you are using?

**Comment by GorgoPrimus** [comment]
Firefox - 114.0.2 (64-bit)

**Comment by mouse0270** [comment]
Oh yeah... I totally forgot to style the slider for firefox and only did it for webkit browsers...

**Comment by mouse0270** [comment]
There we go, this will be fixed in the next version.
![image](https://github.com/mouse0270/kasper/assets/564874/eb8293bb-aeb6-4d68-8a18-f4c4dd813189)

**Comment by GorgoPrimus** [comment]
Thanks!

**Comment by mouse0270** [comment]
Should be resolved in [v1.1.0](https://github.com/mouse0270/kasper/releases/tag/1.1.0)
